import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const {data, refetch, isLoading} = trpc.useQuery(["items.getAll"], {
    refetchInterval: false,
    refetchOnReconnect: false,
    refetchOnWindowFocus: false,
  });

  console.log(isLoading)
  const itemsCreate = trpc.useMutation("items.create");

  async function addItem(){
    itemsCreate.mutate({ name: "test", isBought: false, isOnCart: false });
    refetch()
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="container mx-auto flex flex-col items-center justify-center p-4">
        <h1 className="text-3xl leading-normal font-extrabold text-gray-700 ">
          Box Market
        </h1>

      </header>

      <main>

        <div className="container mx-auto flex flex-col items-center justify-center p-4">
          <h2 className="text-2xl leading-normal font-extrabold text-gray-700 ">
            Items
          </h2>
          <button onClick={() => addItem()} >Adiconar</button>
        </div>

        {data?.map((item) => (
          <div key={item.id} className="container mx-auto flex flex-col items-center justify-center p-4">
            <h2 className="text-2xl leading-normal font-extrabold text-gray-700 ">
              {item.name}
            </h2>
          </div>
        ))}
      </main>
    </>
  );
};

export default Home;